parca-dev/demo-deployments

- grafana-config.yaml
- grafana-datasources.yaml
- grafana-deployment.yaml
Example:
https://demo.parca.dev/grafana/explore?orgId=1&left=%7B%22datasource%22:%22P9B4EE85E4B3B7421%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22datasource%22:%7B%22type%22:%22parca%22,%22uid%22:%22P9B4EE85E4B3B7421%22%7D,%22labelSelector%22:%22%7Bnamespace%3D%5C%22monitoring%5C%22,container%3D%5C%22prometheus%5C%22%7D%22,%22queryType%22:%22both%22,%22profileTypeId%22:%22parca_agent_cpu:samples:count:cpu:nanoseconds:delta%22%7D%5D,%22range%22:%7B%22from%22:%22now-1h%22,%22to%22:%22now%22%7D%7D
> Update Grafana to 9.3.1 and enable Parca core data source

- monitoring/lib/prometheus.libsonnet
We do not have `alertmanager` deployed and RBAC is not there either, it should fix some spamming in the logs:
```
ts=2023-05-12T17:45:35.159Z caller=klog.go:116 level=error component=k8s_client_runtime func=ErrorDepth msg="pkg/mod/k8s.io/client-go@v0.26.2/tools/cache/reflector.go:169: Failed to watch *v1.Pod: failed to list *v1.Pod: pods is forbidden: User \"system:serviceaccount:monitoring:prometheus-parca\" cannot list resource \"pods\" in API group \"\" in the namespace \"monitoring\""
```
```diff
$ argocd app diff scaleway-parca-demo-monitoring --revision=fix/monitoring/disable-alerting
===== monitoring.coreos.com/Prometheus monitoring/parca ======
diff --git a/tmp/argocd-diff2890939402/parca-live.yaml b/tmp/argocd-diff2890939402/parca
index 643590d..167b38d 100644
--- …
```
> fix(monitoring): disable prometheus alerting

- cert-manager/templates/networkpolicy.yaml
- parca/lib/parca-agent.libsonnet
```diff
$ argocd app diff scaleway-parca-demo-parca --revision=fix/parca/agent-netpol
===== networking.k8s.io/NetworkPolicy parca/parca-agent ======
diff --git a/tmp/argocd-diff3468075764/parca-agent-live.yaml b/tmp/argocd-diff3468075764/parca-agent
index 47d6c69..adcaea0 100644
--- a/tmp/argocd-diff3468075764/parca-agent-live.yaml
+++ b/tmp/argocd-diff3468075764/parca-agent
@@ -55,7 +55,7 @@ spec:
- from:
- namespaceSelector:
matchLabels:
-          name: monitoring
+          kubernetes.io/metadata.name: monitoring
podSelector:
matchLabels:
app.kubernetes.io/name: prometheus
```
> fix(parca): fix agent networkpolicy for monitoring

- .schemas/Makefile
- .schemas/application-argoproj-v1alpha1.json
- .schemas/applicationset-argoproj-v1alpha1.json
- .schemas/appproject-argoproj-v1alpha1.json
- README.md
- argocd-applications/README.md
- argocd-applications/environments/scaleway-parca-demo/main.jsonnet
- argocd-applications/environments/scaleway-parca-demo/spec.json
- argocd-applications/lib/utils.libsonnet
- argocd/README.md
- argocd/base/kustomization.yaml
- argocd/base/patches/configure_argocd-cm.yaml
- argocd/base/patches/set_liveness_and_readiness_probes.yaml
- argocd/base/patches/set_resource_limits_and_requests.yaml
- argocd/overlays/scaleway-parca-demo/argocd-server-ingress.yaml
- argocd/overlays/scaleway-parca-demo/files/dex.config.yaml
- argocd/overlays/scaleway-parca-demo/files/policy.csv
- argocd/overlays/scaleway-parca-demo/kustomization.yaml
- cluster-config/base/namespaces.yaml
This configures Argo CD to deploy manifest updates to the demo environment automatically.
The UI is available at: https://demo.parca.dev/argo-cd
It is readable to the public, and admin access is provided to the GitHub team `parca-dev/maintainers`
> feat: add Argo CD

- flux/base/image-reflector-controller/patches/set_resources_limits_requests.yaml
It keeps OOM'ing, something seems wrong with this component, need to look into allocation profiles
> fix(flux): bump image-reflector-controller memory again

- monitoring/environments/scaleway-parca-demo/main.jsonnet
Prometheus is failing to list the pods in the `parca-devel` namespace with the following logs:
```
ts=2023-06-02T14:54:12.451Z caller=klog.go:116 level=error component=k8s_client_runtime func=ErrorDepth msg="pkg/mod/k8s.io/client-go@v0.26.2/tools/cache/reflector.go:169: Failed to watch *v1.Pod: failed to list *v1.Pod: pods is forbidden: User \"system:serviceaccount:monitoring:prometheus-parca\" cannot list resource \"pods\" in API group \"\" in the namespace \"parca-devel\""
```
I think this PR should fix it now.
> Add parca-devel to Prometheus allowed namespaces

- monitoring/environments/scaleway-parca-demo/main.jsonnet
Right now, we only match the pod names, but we also need to have the regex for the namespace.
> Match job for parca-agent and parca-agent-devel

- parca-devel/lib/parca.libsonnet
```diff
===== /ConfigMap parca-devel/parca-devel ======
diff --git a/tmp/argocd-diff3234137050/parca-devel-live.yaml b/tmp/argocd-diff3234137050/parca-devel
index ecf6cf1..402769f 100644
--- a/tmp/argocd-diff3234137050/parca-devel-live.yaml
+++ b/tmp/argocd-diff3234137050/parca-devel
@@ -324,6 +324,7 @@ data:
"own_namespace": false
"role": "endpoints"
"profiling_config":
+        "path_prefix": "devel"
"pprof_config":
"fgprof":
"delta": true
```
> fix(parca-devel): add path_prefix to profilingConfig

- cluster-config/base/namespaces.yaml
- monitoring/environments/scaleway-parca-demo/main.jsonnet
- monitoring/lib/prometheus.libsonnet
This allow to decouple the lifecycles of the namespace and the application, when we remove the application, we do not necessarily want to remove the namespace and everything in it.
Also:
- Explicitly allow traffic from ingress-nginx (it worked as we do not have a deny default policy for now)
- Remove RBAC on `parca-analytics` namespace as this instance is not used to monitor the namespace  
<details>
<summary>cluster-config</summary>
```diff
===== /Namespace /parca-analytics ======
diff --git a/tmp/argocd-diff596013952/parca-analytics-live.yaml b/tmp/argocd-diff596013952/parca-analytics
index e69de29..dd9df17 100644
--- a/tmp/argocd-diff596013952/parca-analytics-live.yaml
+++ b/tmp/argocd-diff596013952/parca-analytics
@@ -0,0 +1,11 @@
+apiVersion: v1
+kind: Namespace
+metadata:
+ …
```
> fix(monitoring): move namespace to cluster-config

- cert-manager/templates/cluster-issuer.yaml
Follow up to #51 
```diff
===== cert-manager.io/ClusterIssuer /letsencrypt-prod ======
diff --git a/tmp/argocd-diff3189961692/letsencrypt-prod-live.yaml b/tmp/argocd-diff3189961692/letsencrypt-prod
index 9b34f94..0be228c 100644
--- a/tmp/argocd-diff3189961692/letsencrypt-prod-live.yaml
+++ b/tmp/argocd-diff3189961692/letsencrypt-prod
@@ -59,7 +59,7 @@ spec:
solvers:
- http01:
ingress:
-          class: nginx
+          ingressClassName: nginx
status:
acme:
lastPrivateKeyHash: Otn/Woxmy3cJrMGep4LcbNDVX3JMjUrqdqiWzEbFeXU=
```
> fix(cert-manager): use ingressClassName

- cluster-config/base/namespaces.yaml
- monitoring/lib/prometheus.libsonnet
```diff
===== monitoring.coreos.com/Prometheus monitoring/parca ======
diff --git a/tmp/argocd-diff267468122/parca-live.yaml b/tmp/argocd-diff267468122/parca
index e4a6b86..c638d73 100644
--- a/tmp/argocd-diff267468122/parca-live.yaml
+++ b/tmp/argocd-diff267468122/parca
@@ -210,6 +210,8 @@ spec:
fsGroup: 2000
runAsNonRoot: true
runAsUser: 1000
+    seccompProfile:
+      type: RuntimeDefault
serviceAccountName: prometheus-parca
serviceMonitorNamespaceSelector: {}
serviceMonitorSelector: {}
===== monitoring.coreos.com/Prometheus parca-analytics/parca-analytics ======
diff --git a/tmp/argocd-diff1527353001/parca-analytics-live.yaml b/tmp/argocd-diff1527353001/parca-analytics
index 73de863..34d6ce9 100644
--- a/tmp/argocd-diff1527353001/parca-analytics-live.yaml
+++ …
```
> fix(monitoring): set prometheus seccompProfile

- cluster-config/base/namespaces.yaml
- ingress-nginx/values.yaml
<details>
<summary>cluster-config</summary>
```diff
===== /Namespace /cert-manager ======
diff --git a/tmp/argocd-diff3484008869/cert-manager-live.yaml b/tmp/argocd-diff3484008869/cert-manager
index 8a6091b..e6438de 100644
--- a/tmp/argocd-diff3484008869/cert-manager-live.yaml
+++ b/tmp/argocd-diff3484008869/cert-manager
@@ -7,6 +7,10 @@ metadata:
{"apiVersion":"v1","kind":"Namespace","metadata":{"name":"cert-manager"}}
labels:
kubernetes.io/metadata.name: cert-manager
+    pod-security.kubernetes.io/audit: restricted
+    pod-security.kubernetes.io/enforce: restricted
+    pod-security.kubernetes.io/enforce-version: v1.24
+    pod-security.kubernetes.io/warn: restricted
managedFields:
- apiVersion: v1
fieldsType: FieldsV1
===== /Namespace /ingress-nginx ======
diff --git …
```
> fix(ingress-nginx): enforce restricted PSA

- monitoring/lib/prometheus-operator.libsonnet
```diff
===== apps/Deployment monitoring/prometheus-operator ======
diff --git a/tmp/argocd-diff2538922502/prometheus-operator-live.yaml b/tmp/argocd-diff2538922502/prometheus-operator
index 66ea265..b745e29 100644
--- a/tmp/argocd-diff2538922502/prometheus-operator-live.yaml
+++ b/tmp/argocd-diff2538922502/prometheus-operator
@@ -311,6 +311,8 @@ spec:
securityContext:
runAsNonRoot: true
runAsUser: 65534
+        seccompProfile:
+          type: RuntimeDefault
serviceAccount: prometheus-operator
serviceAccountName: prometheus-operator
terminationGracePeriodSeconds: 30
===== tanka.dev/Environment /environments/scaleway-parca-demo ======
```
> fix(monitoring): add seccompProfile to prometheus-operator

- .github/workflows/build.yml
I had in mind to use Talos in Civo which has v1.25.5 only, but it does not support Cilium yet. So switching to k3s.
> ci(kubeconform): bump Kubernetes schemas to v1.27.1

- argocd/base/kustomization.yaml
```diff
===== networking.k8s.io/NetworkPolicy argocd/argocd-redis-network-policy ======
diff --git a/tmp/argocd-diff3949817150/argocd-redis-network-policy-live.yaml b/tmp/argocd-diff3949817150/argocd-redis-network-policy
index 8b4c79f..2b6056b 100644
--- a/tmp/argocd-diff3949817150/argocd-redis-network-policy-live.yaml
+++ b/tmp/argocd-diff3949817150/argocd-redis-network-policy
@@ -36,11 +36,7 @@ metadata:
uid: fc18568b-f133-4d2e-8119-b47c1f8d4e83
spec:
egress:
-  - ports:
-    - port: 53
-      protocol: UDP
-    - port: 53
-      protocol: TCP
+  - {}
ingress:
- from:
- podSelector:
```
> fix(argocd): avoid duplicate policyTypes in redis netpol

- README.md
- argocd/README.md
- argocd/overlays/civo-demo/argocd-server-ingress.yaml
- argocd/overlays/civo-demo/kustomization.yaml
- argocd/overlays/scaleway-parca-demo/argocd-server-ingress.yaml
- argocd/overlays/scaleway-parca-demo/kustomization.yaml
Using `demo.parca.dev` creates an awkward dependencies with Parca's certificate. Using its own domain should make bootstrapping a new cluster simpler.
<details>
<summary>diff</summary>
```diff
===== /ConfigMap argocd/argocd-cm ======
diff --git a/tmp/argocd-diff1252284104/argocd-cm-live.yaml b/tmp/argocd-diff1252284104/argocd-cm
index 49a74c8..af0ddc9 100644
--- a/tmp/argocd-diff1252284104/argocd-cm-live.yaml
+++ b/tmp/argocd-diff1252284104/argocd-cm
@@ -23,7 +23,7 @@ data:
clusters:
- '*'
statusbadge.enabled: "true"
-  url: https://demo.parca.dev/argo-cd
+  url: https://argocd.parca.dev
users.anonymous.enabled: "true"
kind: ConfigMap
metadata:
===== apps/Deployment argocd/argocd-server ======
diff --git a/tmp/argocd-diff4139013551/argocd-server-live.yaml …
```
> feat!(argocd): migrate argocd to its own DNS hostname

- ingress-nginx/templates/admission-webhooks-networkpolicy.yaml
Oops it had slip my mind what the netpol was for
> fix(ingress-nginx): restore helm hooks netpol

- grafana/lib/grafana.libsonnet
- parca/lib/parca-agent.libsonnet
- parca/lib/parca.libsonnet
```
metadata.labels: Invalid value: "10.1.2@sha256:63854c5592bab6c7b8ac2ceb35b420925465eb24ef05f2402e4cb805253efb46": must be no more than 63 characters, metadata.labels: Invalid value: "10.1.2@sha256:63854c5592bab6c7b8ac2ceb35b420925465eb24ef05f2402e4cb805253efb46": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue', or 'my_value', or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')
```
This reverts commit e9c99703b82fd9d06daf4bddebd7132f5278bfed.
> revert: remove docker digest from labels

- parca-devel/lib/parca.libsonnet
- parca/lib/parca.libsonnet
I was toying with this, it would allow to use the GRPC protocol to communicate with the demo:
```console
$ grpcurl demo.parca.dev:443 grpc.health.v1.Health/Check
{
"status": "SERVING"
}
```
I saw this client failing with HTTP 415 (Unsupported Media Type), it's in Scaleway, but in another account I think (`parca-load` in Pyrra's account?):
```
51.15.51.214 - - [31/May/2023:19:55:34 +0000] "POST /parca.query.v1alpha1.QueryService/Query HTTP/2.0" 415 63 "-" "grpc-go-connect/1.1.0 (go1.18.10)" 98 0.001 [parca-parca-http] [] 100.64.2.183:7070 72 0.000 415 93c8ab7948a074a26b2435c8cb1808db
```
@metalmatze should it use GRPC-Web under `/api/` like the UI does? Or could we switch it to regular GRPC? 
<details>
<summary>diff</summary>
```diff
===== networking.k8s.io/Ingress parca/parca-grpc ====== …
```
> fix(parca): configure NGINX ingress for GRPC

- cert-manager/templates/cluster-issuer.yaml
This field is now optional and omitted when empty, which creates a diff in Argo CD.
> fix(cert-manager): omit empty preferredChain

- parca-devel/lib/parca-agent.libsonnet
- parca/lib/parca-agent.libsonnet
> **brancz:** We should also increase the limits on the parca agents looks like they get oomkilled a bit too frequently.
https://discord.com/channels/877547706334199818/897027941039505458/1160939748290985985
> **maxbrunet:** `libbpf: prog 'walk_user_stacktrace_impl': BPF program load failed: Argument list too long\n`
> **brancz:** aaaaaahhhhh
> **brancz:** I remember
> **brancz:** we need to remove the verbose bpf logging flag
> **brancz:** it doesn't work on a 5.4 kernel
https://discord.com/channels/877547706334199818/897027941039505458/1160996220936929280
```diff
$ kubectl get node --output=jsonpath='{range .items[*]}{.metadata.name}{"\t"}{.status.nodeInfo.kernelVersion}{"\n"}{end}'
scw-parca-demo-pool-gp1-xs-162ea11cdeb6489192d  5.4.0-148-generic …
```
> fix(parca-agent): bump memory to 1GiB / remove BPF verbose logging

- parca-devel/lib/parca.libsonnet
- parca/lib/parca.libsonnet
> **brancz:** @maxbrunet any idea what changed in the demo cluster? All of the sudden the Parca servers can't always be scheduled anymore with not enough resources being available.
https://discord.com/channels/877547706334199818/897027941039505458/1160939613704179812
Parca will be able to evict other components in order to schedule itself, hopefully other components are small enough to find room on another node.
> fix(parca): bump Parca's priority to cluster critical

- grafana/lib/grafana.libsonnet
The Parca datasource and panel do not support Grafana 10 yet, and Grafana 9 is still supported.
> fix(grafana): downgrade to v9

- monitoring/environments/scaleway-parca-demo/main.jsonnet
```diff
<               name: thanos-objectstorage
---
>               name: parca-analytics-objectstorage
255a256,275
>   volumeClaimTemplates:
>   - apiVersion: v1
>     kind: PersistentVolumeClaim
>     metadata:
>       creationTimestamp: null
>       labels:
>         app.kubernetes.io/component: object-store-gateway
>         app.kubernetes.io/instance: thanos-store
>         app.kubernetes.io/name: thanos-store
>       name: data
>     spec:
>       accessModes:
>       - ReadWriteOnce
>       resources:
>         requests:
>           storage: 10Gi
>       storageClassName: scw-bssd-retain
>       volumeMode: Filesystem
>     status:
>       phase: Pending
```
> Fix object storage name and add PVC to Thanos store

- monitoring/environments/scaleway-parca-demo/main.jsonnet
- monitoring/lib/kube-thanos.libsonnet
```diff
===== networking.k8s.io/NetworkPolicy parca-analytics/prometheus-parca-analytics ======
53a54,60
>   - from:
>     - namespaceSelector:
>         matchLabels:
>           kubernetes.io/metadata.name: parca-analytics
>       podSelector:
>         matchLabels:
>           app.kubernetes.io/name: thanos-query
===== tanka.dev/Environment /environments/scaleway-parca-demo ======
===== networking.k8s.io/NetworkPolicy parca-analytics/thanos-query ======
0a1,19
> apiVersion: networking.k8s.io/v1
> kind: NetworkPolicy
> metadata:
>   annotations:
>     argocd.argoproj.io/tracking-id: scaleway-parca-demo-monitoring:networking.k8s.io/NetworkPolicy:parca-analytics/thanos-query
>   name: thanos-query
>   namespace: parca-analytics
> spec:
>   egress:
>   - to:
>     - namespaceSelector:
> …
```
> Add network policies to kube-thanos

- monitoring/environments/scaleway-parca-demo/main.jsonnet
Instead of connecting to Prometheus with only 1d retention.
```diff
===== networking.k8s.io/Ingress parca-analytics/parca-analytics ======
58c58
<             name: prometheus-parca-analytics
---
>             name: thanos-query
60c60
<               name: web
---
>               name: http
===== networking.k8s.io/NetworkPolicy parca-analytics/thanos-query ======
32a33,45
>   ingress:
>   - from:
>     - namespaceSelector:
>         matchLabels:
>           kubernetes.io/metadata.name: ingress-nginx
>       podSelector:
>         matchLabels:
>           app.kubernetes.io/component: controller
>           app.kubernetes.io/instance: ingress-nginx
>           app.kubernetes.io/name: ingress-nginx
>     ports:
>     - port: http
>       protocol: TCP
===== tanka.dev/Environment …
```
> Direct analytics.parca.dev to thanos-query

- monitoring/README.md
- monitoring/environments/scaleway-parca-demo/main.jsonnet
- monitoring/jsonnetfile.json
- monitoring/jsonnetfile.lock.json
- monitoring/lib/kube-thanos.libsonnet
* Set resources for Thanos query/sidecar/store
* Ensure consistent labeling
* Track kube-thanos `main` branch (upstream PR has been merged)
* Track object storage secret, this is nice to manage its metadata and have a complete view of the deployment from Argo CD
* Ensure sidecar runs the same version as the other components
* Fix Renovate comment
```diff
===== apps/Deployment parca-analytics/thanos-query ======
diff --git a/tmp/argocd-diff1981062498/thanos-query-live.yaml b/tmp/argocd-diff1981062498/thanos-query
index 7559388..8652e38 100644
--- a/tmp/argocd-diff1981062498/thanos-query-live.yaml
+++ b/tmp/argocd-diff1981062498/thanos-query
@@ -218,7 +218,12 @@ spec:
periodSeconds: 5
successThreshold: 1
timeoutSeconds: 1
-        resources: {}
+        resources:
+          limits:
+ …
```
> fix(monitoring): set thanos resources + misc

- parca-devel/lib/parca-agent.libsonnet
```diff
===== apps/DaemonSet parca-devel/parca-agent-devel ======
diff --git a/tmp/argocd-diff4088286657/parca-agent-devel-live.yaml b/tmp/argocd-diff4088286657/parca-agent-devel
index 5958d90..b557aa7 100644
--- a/tmp/argocd-diff4088286657/parca-agent-devel-live.yaml
+++ b/tmp/argocd-diff4088286657/parca-agent-devel
@@ -2,7 +2,7 @@ apiVersion: apps/v1
kind: DaemonSet
metadata:
annotations:
-    argocd.argoproj.io/tracking-id: scaleway-parca-demo-parca-devel:apps/DaemonSet:parca-devel/parca-agent-devel
+    argocd.argoproj.io/tracking-id: argocd_scaleway-parca-demo-parca-devel:apps/DaemonSet:parca-devel/parca-agent-devel
deprecated.daemonset.template.generation: "388"
generation: 388
labels:
@@ -239,6 +239,8 @@ spec:
- --debuginfo-temp-dir=/tmp
- --debuginfo-upload-cache-duration=5m
- …
```
> fix(parca-devel): fix block/mutex profile flags

- ingress-nginx/values.yaml
A flag was added and it is disable by default (kubernetes/ingress-nginx@bfc2300c3d0cd35aa16324b35d865b7a0a6f4bbb)
> fix(ingress-nginx): enable network policy for webhook
